### ISSUE TITLE
Showcase Page - Different cases of same author causes unexpected behaviour

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1029]
When there are multiple submissions with more than one casing of their name, then the author slug formed are the same for them, and only a single casing dominates in the showcase page.

Example: 
![image](https://user-images.githubusercontent.com/59444569/235442815-e3090642-76d0-486f-806a-8d1073abb8a4.png)

![image](https://user-images.githubusercontent.com/59444569/235442839-819b746b-e8cd-415f-9193-e0ac45e6b2a1.png)
(Both the links link to the same page)

![image](https://user-images.githubusercontent.com/59444569/235442866-70aafd3f-8849-4cf4-a2b9-234751766299.png)
(But only one of their contribution is listed)

**Comment by shiffman** [comment]
Oh wow, good catch! Should we manually fix any we find for now but leave this open for finding a more permanent solution later?

**Comment by fturmel** [comment]
Here are a number of dupes surfaced using different tactics. It should be a solid starting point to work on manual corrections.

Let me know if you'd like me to contribute the code so that audits can be run once in a while.

---

### Normalized author urls used by more than one author name

1. github.com/mind0bender Mind0Bender | Yash Gupta
2. github.com/bohdandrahan Bohdan Drahan | bohdandrahan
3. eesur.com Sundar Singh | Sundar Liddar
4. github.com/gypsydangerous David Snyder | David
5. github.com/godeta Arnaud GODET | Godeta | Arnaud Godet
6. greggelong.github.io Greg Kreisman | Gregory Kreisman
7. github.com/joewadsworth JoeWadsworth | Joe Wadsworth
8. editor.p5js.org/kobel/sketches Kobe Liesenborgs | Kobe L
9. github.com/josgielen Jos Gielen | Gielen
10. jcponce.github.io Juan Carlos Ponce Campuzano | Carlos Ponce
11. github.com/ricoloic LOÏC RICO | Loïc Rico
12. github.com/chief141 Chief141 | chief141
13. denisovichdev.github.io/link-tree Denisovich | Rishi | Bhaswar Chakraborty
14. github.com/omareq omareq | Omar Essilfie-Quaye
15. github.com/imtiazkabir Imtiaz Kabir | Md Imtiaz Kabir
16. github.com/diegodelaefe Diego de la Fuente C. | Diego de la Fuente Curaqueo
17. github.com/hugopeeters Hugo Peeters | HugoPeeters
18. chief141.github.io/chiefdev Chief141 | chief141
19. github.com/ygzipekci Yağız İpekçi | Bruce Moerdjiman
20. www.openprocessing.org/user/142183 Carlos | Carlos Angelo
21. github.com/dedowsdi dedowsdi | dwdowsdi
22. github.com/tobiasvonarx Tobias von Arx | tobiasvonarx
23. ednl.github.io ednl | Ewoud Dronkert
24. github.com/butkeraites Renan Butkeraites | Renan Brito Cano Butkeraites
25. github.com/sarvagya230 Sarvagya singh | Sarvagya Singh
26. github.com/ilmnarayana Manikanta Narayana | I L M Narayana
27. twitter.com/chopokopx Sébastien Raynaud | Sebastien Raynaud
28. codepen.io/rajatkantinandi Rajat Kanti Nandi | rajatkantinandi
29. alca.tv Jacob 'Alca' Foster | Jacob Foster
30. github.com/thetastefultoastie TheTastefulToastie | The Tasteful Toastie
31. mattstone.io bigmstone | Matthew Stone
32. github.com/swiftyturtle Fernando Aguilar | SwiftyTurtle
33. github.com/tslytsly Tom Sealey | Tslytsly
34. github.com/a8hay Abhay kumar singh | Abhay singh :>

---

### Matching author names after normalization

1. Bohdan Drahan | bohdandrahan
2. Abhay Kashyap | AbhayKashyap
3. codefish | CodeFish | Codefish
4. pieterdeschepper | Pieter De Schepper
5. Arnaud GODET | Arnaud Godet
6. Heinrich XIAO | Heinrich Xiao
7. JoeWadsworth | Joe Wadsworth
8. LOÏC RICO | Loïc Rico
9. chief141 | Chief141
10. Rajat Kanti Nandi | rajatkantinandi
11. Hugo Peeters | HugoPeeters
12. Abhay singh | Abhay singh :>
13. Venkatakrishnan R | Venkatakrishnan.R
14. tslytsly | Tslytsly
15. Tobias von Arx | tobiasvonarx
16. Sarvagya singh | Sarvagya Singh
17. The Tasteful Toastie | TheTastefulToastie
18. Sébastien Raynaud | Sebastien Raynaud
19. tht_jxny | tht-jxny

---

### Normalized author name compared for low Levenshtein distances
_Noisier, but can help find typos or alternative spellings._

**Distance of 1**
* David | David C.
* dedowsdi | dwdowsdi
* Dom | Tom
* joseph | JosephS
* Martin | Marvin
* stellartux | tellartux
* Tim | Tom



**Distance of 2**
* Akash Y | Akshay
* Alca | Alcina
* Alca | alok
* Anton | Arto
* bongo0 | Gongo
* DeShrike | Shrike
* Dom | M M
* Dom | Sam
* Dom | Tim
* F9Mute | XoMute
* Flixs | oliys
* Harun | Hasan
* Harun | Marc N
* Imtiaz Kabir | Md Imtiaz Kabir
* joseph | Josh
* Krish | Phish
* Krish | Rishi
* Lokesh Kumar | Yogesh Kumar
* M M | Sam
* M M | Tim
* M M | Tom
* Marc N | Martin
* Marc N | Marvin
* Marvin | Marvyn B
* Mor3s | morris
* Paul Keller | Paul Selley
* Radek Titera | Rodak Titěra
* Sam | Tim
* Sam | Tom
* Tika | Tim
* William L | willian



**Distance of 3**
* Abhay Kashyap and Simon Tiger | AbhayKashyap_SimonTiger
* Akshay | Keshav
* Alca | Arnav
* Alca | Arto
* Alca | Ayman
* Alca | Ilija
* Alca | Marc N
* Alca | Tika
* Alca | Vlad
* Alcina | Ilija
* alok | Anton
* alok | Arto
* alok | Carlos
* alok | DasK
* alok | Dom
* alok | khoi
* alok | Syon
* alok | Tom
* alok | Vlad
* Anja Khan | Ashar Khan
* Anton | Ayman
* Anton | dzson
* Anton | Martin
* Anton | Syon
* Anton | Tom
* Ari24 | Arnav
* Ari24 | Arto
* Ari24 | Krish
* Arnav | Arto
* Arnav | Ayman
* Arnav | Bryan
* Arthur | Arto
* Arto | Carlos
* Arto | Harun
* Arto | Marc N
* Arto | Martin
* Arto | sapro
* Arto | Tom
* Ayman | Bryan
* Ayman | Hasan
* Ayman | kaykay
* Ayman | Syon
* Ayman | Tanmay
* Ayman | Yamen
* Boguz | bongo0
* Bryan | Hasan
* Bryan | Syon
* cenkt | Lenus
* Chris O | Krish
* Chris O | Phish
* Chris O | Shrike
* Clipi | Flixs
* Clipi | Ilija
* Clipi | oliys
* Daniel Huang | Daniel Long
* DasK | David
* DasK | Dom
* DasK | dzson
* DasK | Hasan
* DasK | Josh
* DasK | Sam
* David | Marvin
* David C. | Dídac
* Ddone | Dom
* Ddone | dzson
* Ddone | ednl
* Ddone | Syon
* Dídac | Tika
* Dollee | Kora Lee
* Dollee | Sam Lee
* Dom | dzson
* Dom | ednl
* Dom | Josh
* Dom | khoi
* Dom | Rob D
* Dom | Syon
* Donovan | Oon Han
* dzson | Hasan
* dzson | Syon
* ednl | ejer
* ednl | FEDQK
* ednl | Ledii
* ejer | neerb
* FEDQK | Ledii
* Flixs | Ilija
* Gabrz | sapro
* Galitan | Julian
* Gaweph | joseph
* Gielen | Jos Gielen
* Gil Lianni | willian
* Greg Kreisman | Gregory Kreisman
* Harun | Martin
* Harun | Marvin
* Harun | Outrun
* Harun | Serup
* Harun | Yamen
* Hasan | Marc N
* Hasan | Sam
* Hasan | Yamen
* Ilija | oliys
* Ilija | Tika
* João V. | Josh
* JosephS | Josh
* Josh | Krish
* Josh | Phish
* Josh | Rishi
* Josh | Rob D
* Josh | Tom
* Julian | willian
* kaykay | Tanmay
* khoi | Syon
* khoi | Tom
* Kobe L | Rob D
* Kobe L | Toby W
* Ledii | Lenus
* Lenus | Serup
* M M | mmftl
* Marc N | Marvyn B
* Marc N | Mor3s
* Marc N | omareq
* Marc N | Yamen
* Martin | Marvyn B
* Martin | morris
* Marvin | marvszl
* Marvin | morris
* marvszl | Marvyn B
* mdbrim | morris
* mmftl | Mumflr
* olback | oxrock
* Oliver | oliys
* oxke | Tika
* phg98 | Phish
* Phish | Rishi
* Rob D | romibi
* Rob D | Toby W
* Rob D | Tom
* Rob D | Vlad
* Salami | Sam
* Sam | Sam Lee
* Sam | sapro
* Sam | Syon
* Sam | Vlad
* Sam | Yamen
* Sam Lee | Samuel G
* Sam Lee | Yamen
* SebDur | Serup
* Serup | Susul
* Serup | wmrsp
* Shrike | Shriram
* Shriram | Shubham
* sueszli | Susul
* Syon | Tom
* Tanmay | Vanawy
* Thomas P. | Tomato
* Tika | Tom
* Toby W | Tom
* Tom | Tomato
* Tomato | XoMute
* wijhuang | XI ZHANG

**Comment by fturmel** [comment]
#1030 should fix the bug. Maybe we should move my list of author name dupes to a new issue so they can eventually be manually corrected?

**Comment by shiffman** [comment]
@fturmel I'm going to work on fixing some manually now then will close this issue after I do so!

**Comment by shiffman** [comment]
Closing this, we can continue to clean up as needed!
