### ISSUE TITLE
Missing Meta Images

### ISSUE THREAD

**Issue by M0nica** [CodingTrain/thecodingtrain.com#170]
It looks like the head of the website is missing a meta images to render in previews when the link is shared. https://github.com/CodingTrain/thecodingtrain.com/blob/main/src/components/Head.js If it's confirmed that this is an issue, are there pre-made images that should be used for the meta images?

<img width="595" alt="Screen Shot 2022-06-06 at 3 20 37 PM" src="https://user-images.githubusercontent.com/6998954/172231990-8d54d07f-5022-4644-b93d-d5f0049c8001.png">
Screenshot from https://metatags.io/

**Comment by shiffman** [comment]
Oh, this is a great point! I'm also thinking I might like to make some minor edits to the meta sentence that's included.

All of the track and video pages have a thumbnail image associated with them (usually called `index.png` or `index.jpg`) would it make sense to use this when available? Otherwise we could probably design a single preview image it could be the train image on the homepage or something else. @jasontheillustrator might have some ideas! @fdoflorenzano let us know if you have thoughts too!

Should we also have a favicon?

**Comment by fdoflorenzano** [comment]
Hey! The referenced component should be easily extendable so support this. Using that and the Layout component, if the page has an associated thumbnail, use that as meta image, and if not use a default image as meta.

**Comment by shiffman** [comment]
This can be closed with #207 I believe! I'll wait a bit in case @M0nica wants to double-check the implementation and how it looks now!

**Comment by M0nica** [comment]
Great, it looks like https://github.com/CodingTrain/thecodingtrain.com/pull/207 resolves this.
