### ISSUE TITLE
No "Source Code" Link for Passenger Showcase

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#244]
For any contribution, the image and title links to the actual project (`url`), while the name of the creator links to their page (`author.url`)

![image](https://user-images.githubusercontent.com/59444569/173191820-013178d5-5e5a-43fe-a547-653323beb77f.png)

From the website, there is no way to open the source code of the contribution (`source`). Is this intentional? Nonetheless, this makes the `source` field in the contribution pointless.

**Comment by shiffman** [comment]
Ah, this is an oversight! The `source` field is technically optional but it would be nice to link to it if it's there. I don't know if it'll make it too busy with the purple "play" icon but we could have a source code icon in the bottom right or top right? @fdoflorenzano @runemadsen what do you think?

**Comment by fdoflorenzano** [comment]
To be clear, it was intentional about how we originally proposed it. The way this part was thought is that there's multiple ways of adding a showcase reference: `url`, `videoId` or `source`. The priority to actualy use is `url`, then `videoId` , and finally `source`. So`source` is not really pointless on it's own, it's pointless adding it with other types of sources because they have preference. I guess they didn't notice this when writing the contribution guide.

I guess we can try adding more icons in case they're there, but with the video option too it can get tricky really fast.

**Comment by kfahn22** [comment]
I had noticed this, but decided that if anyone wanted to look at the code for a (p5 sketch) contribution  it is easy enough to modify  the link from Fullscreen to Edit.

**Comment by shiffman** [comment]
Ah, thank you for clarifying @fdoflorenzano, this was my confusion! 

I think we can actually simplify this and only have `url`. `videoId` is not necessary since if the shared media is a video that can just be linked via the `url` property. The video is not being displayed / embedded here so we don't need to treat it as a special case.

These are probably 95% of the cases:

url:
* link to p5 web editor (includes source)
* link to open processing, codepen, or some other online editor (includes source)
* link to blog post documentation (which could separately link to source)

There are some rare cases where the url might link to:

* video on YouTube
* Deployed website

So I suppose for these rare ones we could allow an additional "optional" `source` property, but I'm also fine with just removing it entirely and saying a showcase submission is only:

```json
{
  "title": "project name",
  "url": "project url",
  "author": {
    "name": "Your Name (or nickname!)",
    "url": "Link to more about you! (your personal site, GitHub, social media, etc.)"
  }
}
```
After all a YouTube video could link to the source in the description and a deployed website could have an "about" page. There's no requirement that people submit "open source" projects, the point it just to share their creativity!

Can anyone think of any reason why we need to keep `source` or `videoId`?

**Comment by runemadsen** [comment]
I like that a lot. If we eventually want to show submission videos, we should be able to easily extract it from the URL. The only thing is the icon handling, but if it's just an URL field, maybe we just go with a single icon?

**Comment by kfahn22** [comment]
I would agree that you don't need a separate source link. FYI, in adding the contributions, I would estimate (very, very  roughly) the 10% were a link to a youTube video, 10% were to a personal website, 20% to codepen, and then the remaining were p5 sketches and GitHub repos.

**Comment by shiffman** [comment]
> I like that a lot. If we eventually want to show submission videos, we should be able to easily extract it from the URL. The only thing is the icon handling, but if it's just an URL field, maybe we just go with a single icon?

Hi @runemadsen can you clarify what you mean by "icon"—the "play" button in the corner? It works for me to just have one icon for everything. It's not important to me to distinguish between submissions that are videos vs. p5 sketches etc.  (If you prefer I don't even think we need the icon it can just be a clickable image. But I defer to you all in terms of the design!)

![image](https://user-images.githubusercontent.com/191758/174473511-f5684644-ad49-4092-a2d0-85c34a58dbb9.png)

**Comment by runemadsen** [comment]
Yes, that's the icon I meant! I agree that we should just remove it and have the image link to the submission.

**Comment by shiffman** [comment]
I think this is resolved and can be closed! Feel free to comment or re-open if I've missed something.
