### ISSUE TITLE
Netlify Build issue?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#264]
Hi @runemadsen! Running into an error where the build is "taking too long" and timing out on Netlify. See #261 

<img width="738" alt="Screen Shot 2022-06-13 at 6 34 35 PM" src="https://user-images.githubusercontent.com/191758/173401987-1a94f791-bcad-4164-8760-3f817a08ba4d.png">

I'm presently in the middle of a local build and will update here if it finished successfully.

<img width="909" alt="Screen Shot 2022-06-13 at 6 34 50 PM" src="https://user-images.githubusercontent.com/191758/173402041-ba09649d-5af9-47db-bd5e-2e834a22dba6.png">

Could this be an issue now that the site has many more pages? Is running `npm run clean` for every single deployment a problem?

<img width="982" alt="Screen Shot 2022-06-13 at 6 36 59 PM" src="https://user-images.githubusercontent.com/191758/173402233-a599c093-4645-437f-bf95-7dd1a21321df.png">

Maybe we can address this over dessert?

**Comment by shiffman** [comment]
The local build completed but the page queries did take 904 seconds!

![image](https://user-images.githubusercontent.com/191758/173404272-bbf61e92-b85d-4a66-9c3c-f0af74aeeb8b.png)

**Comment by runemadsen** [comment]
Looking at this now! I'm going to try to upgrade to Gatsby v4, and then take a look at whether we need to downsize some of the images / add build caching to Netlify.

**Comment by runemadsen** [comment]
After looking into this yesterday, there's a number of factors leading to this happening:

- The build time on Netlify (+30m) is significantly higher than on my local machine (5m). This must be caused by Netlify's build machines having much less power than my local one
- Many images were above 1mb. This is an issue since every build resizes the images, and larger images seem to have an exponential effect on the build time. Netlify should in theory cache the image resize results and use them in the next build if they didn't change, but that doesn't seem to be happening despite updated the Netlify Gatsby plugin.
- Gatsby will automatically create 3 sizes of each image to use for responsive designs. We might be able to run through the site and tweak that functionality for images that are just shown in small such as the showcase images

@shiffman Here's what I suggest for next steps:
- Contact Netlify and ask if they can increase the build time (@shiffman)
- Run through the repo and resize all showcase images to 800-100px max (?)
- Check the gatsby setup when resizing responsive images and see if there are any performance gains (@runemadsen)

Does that sound okay to you?

**Comment by shiffman** [comment]
@runemadsen yes, this sounds like a great plan! Could the fact that I am running `npm run clean && npm run build` be the issue related to the image resize results not caching? I added `npm run clean` when some aspects of the site weren't updating properly after a build, but we might have only thought this was happening due to a longer build time!

I can try removing that and see.

Yay!

**Comment by runemadsen** [comment]
Excellent. As long as you're just running `clean` on your local machine, it shouldn't be able to affect the build process on Netlify. But it will slow down your local build time.

**Comment by shiffman** [comment]
Ah, but I am running it on Netlify itself! (not locally). I'm going to take that out now and see if that improves anything.

<img width="1031" alt="Screen Shot 2022-06-15 at 10 14 34 AM" src="https://user-images.githubusercontent.com/191758/173777664-3d49f2cd-69a4-4c0e-a876-fbe735079cbd.png">

**Comment by jlengstorf** [comment]
Hi!

A couple quick things:

1. I have requested a build limit increase, so the timeout should stop. 
2. Running clean removes the cache, so it drastically increases the build time. 
3. Image optimization is one of the biggest culprits in long Gatsby builds. Resizing those images down the the largest size you need them (keep 2x density in mind!) will make a big difference. 

Does this site run the Netlify Gatsby plugin when it builds? That will further speed up builds if it’s not already in place. Search “Gatsby” here to install: https://app.netlify.com/plugins

Let me know if I can help with anything else!

**Comment by runemadsen** [comment]
Thanks @jlengstorf!

We just upgraded to version 3 of the Netlify Gatsby plugin last week, and I think that helped a bit. We'll downsize images and see how fast we can get it to build :) 

Rune

**Comment by shiffman** [comment]
I don't want to jinx it build the build has doubled in speed and is now coming in around 15 minutes. . will keep this thread open for a bit longer but as of now it is all good by me!
