### ISSUE TITLE
Multi-Part Challenges break a side track

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#738]
At the moment, we cannot include multi-part challenges in a side track, see an example here:

https://thecodingtrain.com/tracks/games/46-asteroids

@lobertrand what do you think the best way to handle this is? 

@kfahn22 do you think we should remove them temporarily until we have this resolved?

**Comment by lobertrand** [comment]
Hello, I guess one way to handle this could "spread" the multiple parts on the track, something like this : 
![image](https://user-images.githubusercontent.com/37326143/198372798-a563f172-ecb8-4de2-83b4-12b4f77c21bc.png)
I don't know how hard that would be to implement but I'm willing to try :smiley:

**Comment by kfahn22** [comment]
Yes I will remove

**Comment by shiffman** [comment]
Once this is resolved we can revert #739

**Comment by shiffman** [comment]
@lobertrand this seems like a great solution to me!

**Comment by lobertrand** [comment]
Hi @shiffman @kfahn22 :steam_locomotive: 
I'm working on fixing this issue and I was wondering which title I should display in the timeline for multi-part challenges.
If we take this example : 
```json
{
  "title": "Agar.io",
  "parts": [
    { "title": "Agar.io - Part 1 (Basic Game Mechanics)" },
    { "title": "Agar.io - Part 2 (Networking with Socket.IO and Node.js)" }
  ]
}
```
Which way should we display the title?
A. `video.parts[*].title`
![image](https://user-images.githubusercontent.com/37326143/198888045-bdaea5b9-7993-43d0-a1b2-fafb4364ae3e.png)
B. `video.title - Part #`
![image](https://user-images.githubusercontent.com/37326143/198888084-7b1531da-e46e-40f1-a9b5-8c63864539fa.png)

Option A works great with the above example but less with the following ones: 
```json
{
  "title": "Polar Noise Loops",
  "parts": [
    { "title": "Polar Perlin Noise Loops" },
    { "title": "Perlin Noise GIF Loops" }
  ]
}
```
```json
{
  "title": "Traveling Salesperson",
  "parts": [
    { "title": "Part 1: Traveling Salesperson (TSP)" },
    { "title": "Part 2: Lexicographic Order" },
    { "title": "Part 3: TSP with Lexicographic Order" },
    { "title": "Part 4: TSP with Genetic Algorithm" },
    { "title": "Part 5: TSP with Genetic Algorithm and Crossover" }
  ]
}
```
![image](https://user-images.githubusercontent.com/37326143/198889382-37283287-3e0a-409a-a32b-291d4fb692e3.png)

Since the title of these parts don't include the name of the challenge itself, we cannot easily tell that they are parts of the same challenge.

I think we should homogenize the way part titles are formatted in the JSON files. The question is, should they include the name of the challenge? or just something like this (which eliminates data redundancy): 
```json
{
  "title": "Agar.io",
  "parts": [
    { "title": "Part 1 (Basic Game Mechanics)" },
    { "title": "Part 2 (Networking with Socket.IO and Node.js)" }
  ]
}
```

**Comment by dipamsen** [comment]
In my opinion, the part title should not contain the challenge title, only Part #, and/or the part-specific title.

**Comment by kfahn22** [comment]
I guess you could make a good argument either way.  Another consideration is that whatever is chosen will affect the YouTube description that is generated.

**Comment by dipamsen** [comment]
> Another consideration is that whatever is chosen will affect the YouTube description that is generated.  (Or maybe not, is it always just Part 2, Part 3 regardless of what the title is?)

In the YouTube description, currently the part-specific title is used to link to other parts of the video.

**Comment by lobertrand** [comment]
@kfahn22 @dipamsen Thanks for the feeback!
@shiffman I'm gonna call PR #743 done, not using the part-specific titles for now
I'll open a new PR to homogenize the part-specific titles and adjust their usage accordingly :smiley:

**Comment by shiffman** [comment]
Fantastic! Sounds good, I don't think it's a big deal if we don't have the part specific titles so am fine with leaving as is too!
