### ISSUE TITLE
Video page indexing: "Google could not determine the prominent video on the page"

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#990]
I received this email notification from google indexing, I don't know if this is important or meaningful but I thought I would file it here:

> Video page indexing issues detected in thecodingtrain.com
> To the owner of thecodingtrain.com:
> Search Console has identified that your site is affected by 1 Video page indexing issue(s). The following issues were found on your site.
> Google could not determine the prominent video on the page
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

Video page | Video URL | Last crawled
-- | -- | --
https://thecodingtrain.com/challenges/1-starfield/ | https://www.youtube.com/embed/17WoOqgXsRM?autoplay=0&rel=0&enablejsapi=1&origin=https://thecodingtrain.com&widgetid=1 | 2023-03-29
https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/5-functions/1-basics | https://www.youtube.com/embed/wRHAitGzBrg?autoplay=0&rel=0&enablejsapi=1&origin=https://thecodingtrain.com&widgetid=1

**Comment by fturmel** [comment]
Not sure what the implications of this are in terms of SEO.

This is probably happening because the YouTube iframe is not in the static HTML page built by Gatsby and only injected client-side by React (using https://github.com/tjallingt/react-youtube, which wraps this other library https://github.com/gajus/youtube-player).

<img width="775" alt="Screenshot 2023-04-02 at 12 38 51 PM" src="https://user-images.githubusercontent.com/4009209/229366538-a351f128-e6b8-4d18-a07e-c6813ac59097.png">

The site needs a reference to the JS player to jump to timestamps without reloading the iframe every time.

If the current approach becomes a problem, it should be possible to explore different implementations of the YouTube player. https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player

**Comment by shiffman** [comment]
Ah, thanks for the helpful context @fturmel. I'll leave this issue open for now, but will consider it low priority.

**Comment by shiffman** [comment]
I propose closing this issue, it hasn't come up again and doesn't bother me?

**Comment by fturmel** [comment]
Agreed, especially if you haven't received more alerts and there is no measurable SEO impact.
